[package]
name = "voidb-plugin-redis"
version = "0.3.0-rc.1"
edition = "2024"
license.workspace = true

[dependencies]
voidb-core = { path = "../../voidb-core" }
redis = { version = "0.27", features = ["tokio-comp", "aio", "streams"] }
futures-util = "0.3"
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
