[package]
name = "voidb-plugin-duckdb"
version = "0.3.0-rc.1"
edition = "2024"
license.workspace = true

[dependencies]
voidb-core = { path = "../../voidb-core", default-features = false }
duckdb = { version = "1.4", features = ["bundled"] }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
hex = "0.4"
